name: Publish to WinGet
on: push
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: ThaUnknown.Miru
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}